workflows:
  ios-release:
    name: iOS Release → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "ios-v*"
          include: true

    environment:
      groups:
        - appstore_credentials

      # One signing strategy only: uploaded profile + cert references
      ios_signing:
        provisioning_profiles:
          - aSpiral_iOS_AppStoreConnect_2026
        certificates:
          - aSpiral_dist_2026

      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        IOS_INFO_PLIST: ios/App/App/Info.plist
        IOS_IPA_PATH: build/ios/ipa/aSpiral.ipa

      node: 22
      xcode: 26.1
      cocoapods: default

    scripts:
      - name: Preflight — normalize ASC env vars (KEY_IDENTIFIER)
        script: |
          set -euo pipefail

          # Required (matches Codemagic docs)
          test -n "${APP_STORE_CONNECT_PRIVATE_KEY:-}" || (echo "Missing APP_STORE_CONNECT_PRIVATE_KEY" && exit 1)
          test -n "${APP_STORE_CONNECT_ISSUER_ID:-}" || (echo "Missing APP_STORE_CONNECT_ISSUER_ID" && exit 1)

          # Normalize Key ID: accept multiple historical spellings / casing
          ASC_KEY_ID=""
          if [ -n "${APP_STORE_CONNECT_KEY_IDENTIFIER:-}" ]; then
            ASC_KEY_ID="${APP_STORE_CONNECT_KEY_IDENTIFIER}"
          elif [ -n "${APP_STORE_CONNECT_KEY_ID:-}" ]; then
            ASC_KEY_ID="${APP_STORE_CONNECT_KEY_ID}"
          elif [ -n "${APP_STORE_CONNECT_KEY_iD:-}" ]; then
            ASC_KEY_ID="${APP_STORE_CONNECT_KEY_iD}"
          else
            echo "Missing Key ID env var. Expected APP_STORE_CONNECT_KEY_IDENTIFIER (preferred)."
            echo "Also accepts APP_STORE_CONNECT_KEY_ID or APP_STORE_CONNECT_KEY_iD."
            exit 1
          fi

          # Persist normalized name for ALL subsequent steps (Codemagic CM_ENV mechanism)
          echo "APP_STORE_CONNECT_KEY_IDENTIFIER=${ASC_KEY_ID}" >> "$CM_ENV"

          echo "✅ ASC auth vars present (KEY_IDENTIFIER normalized)"

      - name: Install dependencies
        script: |
          set -euo pipefail
          npm ci

      - name: Unit tests (app only — avoid supabase/functions tests)
        script: |
          set -euo pipefail
          if npx vitest --version >/dev/null 2>&1; then
            npx vitest run src
          else
            echo "Vitest not found; skipping tests."
          fi

      - name: Build web assets
        script: |
          set -euo pipefail
          npm run build

      - name: Sync Capacitor (iOS)
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: Verify iOS web assets copied (prevents blank purple shell)
        script: |
          set -euo pipefail
          test -f ios/App/App/public/index.html || (echo "Missing ios/App/App/public/index.html after cap sync" && exit 1)

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios/App
          pod install

      - name: Set iOS version from tag (ios-vX.Y.Z) + build number
        script: |
          set -euo pipefail
          VERSION="${CM_TAG#ios-v}"
          BUILD_NO="${BUILD_NUMBER:-1}"
          echo "Setting iOS version to ${VERSION} (${BUILD_NO})"

          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${VERSION}" "$IOS_INFO_PLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${VERSION}" "$IOS_INFO_PLIST"

          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_NO}" "$IOS_INFO_PLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${BUILD_NO}" "$IOS_INFO_PLIST"

      - name: TestFlight internal only export option
        script: |
          set -euo pipefail
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'

      - name: Build iOS IPA
        script: |
          set -euo pipefail
          mkdir -p build/ios/ipa
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --ipa-path "$IOS_IPA_PATH"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        # Codemagic supports env-var auth for publishing:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Internal Testers

      email:
        recipients:
          - michael@apexbiz.io
        notify:
          success: true
          failure: true
