workflows:
  aspiral_ios_testflight:
    name: aSpiral iOS → TestFlight (API key + auto signing)
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      xcode: 16.4
      node: 20
      cocoapods: default

      groups:
        - appstore_credentials

      vars:
        TEAM_ID: NWGUYF42KW
        BUNDLE_ID: com.apex.tradeline

        # These will exist after cap sync (we verify)
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        INFO_PLIST_PATH: ios/App/App/Info.plist

        IOS_IPA_PATH: build/ios/ipa/aSpiral.ipa

    scripts:
      - name: Preflight (required env + normalize KEY_ID)
        script: |
          set -euo pipefail

          # Normalize common Key ID var drift (case issues)
          KEY_ID="${APP_STORE_CONNECT_KEY_ID:-${APP_STORE_CONNECT_KEY_iD:-${APP_STORE_CONNECT_KEY_IDENTIFIER:-}}}"

          if [ -z "${APP_STORE_CONNECT_ISSUER_ID:-}" ] || [ -z "${APP_STORE_CONNECT_PRIVATE_KEY:-}" ] || [ -z "$KEY_ID" ]; then
            echo "Missing App Store Connect API key env vars."
            echo "Need: APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_PRIVATE_KEY, and one of KEY_ID/KEY_IDENTIFIER."
            exit 1
          fi

          echo "APP_STORE_CONNECT_KEY_ID=$KEY_ID" >> "$CM_ENV"

          for v in TEAM_ID BUNDLE_ID; do
            if [ -z "${!v:-}" ]; then
              echo "Missing required env var: $v"
              exit 1
            fi
          done

          echo "Preflight OK"
          echo "TEAM_ID=$TEAM_ID"
          echo "BUNDLE_ID=$BUNDLE_ID"

      - name: Install JS deps
        script: |
          set -euo pipefail
          node -v
          npm -v
          npm ci

      - name: Build web assets
        script: |
          set -euo pipefail
          npm run build

      - name: Sync Capacitor iOS
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: Verify iOS workspace/plist exists after sync
        script: |
          set -euo pipefail
          if [ ! -d "$XCODE_WORKSPACE" ]; then
            echo "Missing workspace: $XCODE_WORKSPACE"
            echo "Listing ios/App:"
            ls -la ios/App || true
            exit 1
          fi
          if [ ! -f "$INFO_PLIST_PATH" ]; then
            echo "Missing Info.plist: $INFO_PLIST_PATH"
            exit 1
          fi

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios/App
          pod install
          cd -

      - name: Initialize keychain
        script: |
          set -euo pipefail
          keychain initialize

      - name: Fetch signing files (App Store) + import certs (AUTO)
        script: |
          set -euo pipefail
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates

      - name: Set version + unique build number (TestFlight-safe)
        script: |
          set -euo pipefail
          VERSION="${CM_TAG#ios-v}"
          if [ -z "${VERSION}" ] || [ "${VERSION}" = "${CM_TAG}" ]; then
            VERSION="1.0.0"
          fi

          BUILD="$(date -u +%Y%m%d%H%M%S)"

          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $VERSION" "$INFO_PLIST_PATH" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string $VERSION" "$INFO_PLIST_PATH"

          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD" "$INFO_PLIST_PATH" || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD" "$INFO_PLIST_PATH"

          echo "BUILD_NUMBER=$BUILD" >> "$CM_ENV"
          echo "Version=$VERSION Build=$BUILD"

      - name: Configure code signing (uses fetched profiles)
        script: |
          set -euo pipefail
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'

      - name: Build IPA
        script: |
          set -euo pipefail
          mkdir -p build/ios/ipa
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --ipa-path "$IOS_IPA_PATH"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
