workflows:
  aspiral_ios_testflight:
    name: aSpiral iOS → TestFlight (Green Lane)
    instance_type: mac_mini_m2
    max_build_duration: 90

    environment:
      xcode: 16.4
      cocoapods: default
      node: 22
      groups:
        - ios_credentials
        - appstore_credentials
      vars:
        NODE_OPTIONS: "--max_old_space_size=8192"

        # Repo-known path (from your logs)
        INFO_PLIST_PATH: "ios/App/App/Info.plist"
        XCODE_SCHEME: "App"

        # Workspace candidates
        XCODE_WORKSPACE_PRIMARY: "ios/App/App.xcworkspace"
        XCODE_WORKSPACE_FALLBACK: "ios/App/App.xcodeproj/project.xcworkspace"

    scripts:
      - name: Preflight (fail fast + normalize env)
        script: |
          set -euo pipefail

          # Normalize Key ID naming drift:
          # Codemagic App Store Connect CLI expects APP_STORE_CONNECT_KEY_IDENTIFIER
          KEY_IDENTIFIER="${APP_STORE_CONNECT_KEY_IDENTIFIER:-}"

          if [ -z "${KEY_IDENTIFIER}" ] && [ -n "${APP_STORE_CONNECT_KEY_ID:-}" ]; then
            KEY_IDENTIFIER="${APP_STORE_CONNECT_KEY_ID}"
          fi

          if [ -z "${KEY_IDENTIFIER}" ] && [ -n "${APP_STORE_CONNECT_KEY_iD:-}" ]; then
            KEY_IDENTIFIER="${APP_STORE_CONNECT_KEY_iD}"
          fi

          if [ -z "${KEY_IDENTIFIER}" ]; then
            echo "❌ Missing App Store Connect Key ID. Provide APP_STORE_CONNECT_KEY_IDENTIFIER (or KEY_ID/KEY_iD)."
            exit 1
          fi

          # Persist for ALL later steps + publishing
          echo "APP_STORE_CONNECT_KEY_IDENTIFIER=${KEY_IDENTIFIER}" >> "$CM_ENV"

          for v in TEAM_ID APP_STORE_CONNECT_ISSUER_ID APP_STORE_CONNECT_PRIVATE_KEY CERTIFICATE_PRIVATE_KEY; do
            if [ -z "${!v:-}" ]; then
              echo "❌ Missing required env var: $v"
              exit 1
            fi
          done

          test -f package.json || (echo "❌ package.json missing at repo root" && exit 1)
          test -f "${INFO_PLIST_PATH}" || (echo "❌ Info.plist missing at ${INFO_PLIST_PATH}" && exit 1)

          echo "✅ Preflight OK"
          echo "TEAM_ID=${TEAM_ID}"

      - name: Pin npm (matches known-good lane behavior)
        script: |
          set -euo pipefail
          node -v
          npm install -g npm@10
          npm -v

      - name: Install JS deps
        script: |
          set -euo pipefail
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm ci

      - name: Build web assets
        script: |
          set -euo pipefail
          export NODE_OPTIONS="--max_old_space_size=8192"
          npm run build

      - name: Capacitor sync iOS
        script: |
          set -euo pipefail
          npx cap sync ios

      - name: CocoaPods (ONLY if Podfile exists)
        script: |
          set -euo pipefail
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App
            pod install
            cd ../..
            echo "✅ CocoaPods installed"
          else
            echo "ℹ️ No Podfile found. Skipping pod install (SPM-only Capacitor project)."
          fi

      - name: Resolve iOS build target (workspace vs project) + detect bundle id
        script: |
          set -euo pipefail

          if [ -d "${XCODE_WORKSPACE_PRIMARY}" ]; then
            XCODE_WORKSPACE="${XCODE_WORKSPACE_PRIMARY}"
          elif [ -d "${XCODE_WORKSPACE_FALLBACK}" ]; then
            XCODE_WORKSPACE="${XCODE_WORKSPACE_FALLBACK}"
          else
            echo "❌ No Xcode workspace found."
            echo "Listing ios/App:"
            ls -la ios/App || true
            exit 1
          fi

          echo "XCODE_WORKSPACE=${XCODE_WORKSPACE}" >> "$CM_ENV"
          echo "✅ Using workspace: ${XCODE_WORKSPACE}"

          # Detect PRODUCT_BUNDLE_IDENTIFIER (prevents wrong env like com.apex.tradeline)
          BUNDLE_ID_DETECTED="$(xcodebuild -showBuildSettings \
            -workspace "${XCODE_WORKSPACE}" \
            -scheme "${XCODE_SCHEME}" \
            -configuration Release 2>/dev/null \
            | awk -F' = ' '/PRODUCT_BUNDLE_IDENTIFIER/ {print $2; exit}')"

          if [ -z "${BUNDLE_ID_DETECTED:-}" ]; then
            if [ -n "${BUNDLE_ID:-}" ]; then
              BUNDLE_ID_DETECTED="${BUNDLE_ID}"
              echo "⚠️ Could not detect bundle id; falling back to env BUNDLE_ID=${BUNDLE_ID_DETECTED}"
            else
              echo "❌ Could not detect bundle id and no BUNDLE_ID env var set."
              exit 1
            fi
          fi

          echo "BUNDLE_ID=${BUNDLE_ID_DETECTED}" >> "$CM_ENV"
          echo "✅ Bundle ID: ${BUNDLE_ID_DETECTED}"

      - name: Set unique build number (TestFlight-safe)
        script: |
          set -euo pipefail
          BUILD="$(date -u +%Y%m%d%H%M%S)"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD}" "${INFO_PLIST_PATH}" \
            || /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${BUILD}" "${INFO_PLIST_PATH}"
          echo "✅ Build number set: ${BUILD}"

      - name: Initialize keychain + fetch/create signing files (explicit key vars)
        script: |
          set -euo pipefail

          : "${BUNDLE_ID:?BUNDLE_ID missing}"
          : "${APP_STORE_CONNECT_ISSUER_ID:?APP_STORE_CONNECT_ISSUER_ID missing}"
          : "${APP_STORE_CONNECT_KEY_IDENTIFIER:?APP_STORE_CONNECT_KEY_IDENTIFIER missing}"
          : "${APP_STORE_CONNECT_PRIVATE_KEY:?APP_STORE_CONNECT_PRIVATE_KEY missing}"
          : "${CERTIFICATE_PRIVATE_KEY:?CERTIFICATE_PRIVATE_KEY missing}"

          keychain initialize

          # Explicit flags prevent the CLI from failing on env-name drift
          app-store-connect fetch-signing-files "${BUNDLE_ID}" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "${APP_STORE_CONNECT_ISSUER_ID}" \
            --key-id "${APP_STORE_CONNECT_KEY_IDENTIFIER}" \
            --private-key @env:APP_STORE_CONNECT_PRIVATE_KEY \
            --certificate-key @env:CERTIFICATE_PRIVATE_KEY

          keychain add-certificates
          echo "✅ Signing assets ready"

      - name: Configure code signing (Internal Testing Only)
        script: |
          set -euo pipefail
          xcode-project use-profiles --custom-export-options='{"testFlightInternalTestingOnly": true}'
          echo "✅ Profiles applied"

      - name: Build IPA
        script: |
          set -euo pipefail
          xcode-project build-ipa --workspace "${XCODE_WORKSPACE}" --scheme "${XCODE_SCHEME}"

      - name: Verify IPA + export IPA_PATH
        script: |
          set -euo pipefail
          IPA="$(ls -1 build/ios/ipa/*.ipa 2>/dev/null | head -n 1 || true)"
          if [ -z "${IPA:-}" ]; then
            echo "❌ IPA not found in build/ios/ipa"
            echo "Listing build/ios:"
            ls -la build/ios || true
            exit 1
          fi
          echo "✅ IPA: ${IPA}"
          echo "IPA_PATH=${IPA}" >> "$CM_ENV"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
