sonar.projectKey=aSpiral
sonar.sources=src
sonar.exclusions=coverage/**,dist/**,**/*.test.ts,**/*.test.tsx
sonar.cpd.exclusions=coverage/**,dist/**,**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=Web:UnknownProperty
sonar.issue.ignore.multicriteria.e1.resourceKey=src/components/**/*.tsx
sonar.issue.ignore.multicriteria.e2.ruleKey=javascript:S6730
sonar.issue.ignore.multicriteria.e2.resourceKey=src/components/**/*.tsx
